version: '3.8'
services:
  web:
    build: .
    restart: always
    volumes:
      - ./models:/app/models
    ports:
      - "8000:8000"

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/letsencrypt:ro
    depends_on:
      - web
