version: '3.8'
services:
  web:
    build: .
    restart: always
    volumes:
      - ./models:/app/models
    # Expose port 8000 only to other services on the docker-compose network
    # (do not publish to the host). This forces external traffic to go through nginx
    # which listens on host port 80/443 and proxies to the `web` service.
    expose:
      - "8000"

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/letsencrypt:ro
    depends_on:
      - web
